name: Release
on:
  push:
    tags:
      - 'v*.*.*'
defaults:
  run:
    shell: bash
jobs:
  autobutler-release:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FG_PAT }}
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            github.rest.actions.createWorkflowDispatch({
              owner: 'autobutler-org',
              repo: 'autobutler.org',
              workflow_id: 'release.yml',
              ref: 'main',
              inputs: {
                tag: tag,
              }
            });
